![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
# import matplotlib solo quería anotarlo en alguna parte
import numpy as np 
my_array = np.array(np.arange(10))
print(my_array)
print("___________________________________\n")
print(np.flip(my_array))

[0 1 2 3 4 5 6 7 8 9]
___________________________________

[9 8 7 6 5 4 3 2 1 0]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
print(my_array[[8,7]])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
print(my_array[[2,1,0]])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [6]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [12]:
Ejercicio_5 = np.arange(1, 21).reshape(4, 5)
nuevo_Array2 = Ejercicio_5[0:2, 0:2]
print(nuevo_Array2)


[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [11]:
Ejercicio_6 = np.arange(1, 21).reshape(4, 5)
nuevo_Array3 = Ejercicio_6[[0, 2], ::2]
print(nuevo_Array3)


[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [10]:
Ejercicio_7 = np.arange(1, 21).reshape(4, 5)
nuevo_Array4 = Ejercicio_7[0:3, ::-1]
print(nuevo_Array4)


[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [18]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)
print()
animal_Escogido = np.where(x == "Loro")
print(animal_Escogido)
print()
loros = x[animal_Escogido]
print(loros)


['Loro' 'Perro' 'Gato' 'Loro' 'Perro']

(array([0, 3]),)

['Loro' 'Loro']


In [14]:
loros = x[x == "Loro"]
print(loros)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [19]:
Ejercicio_9 = np.arange(20).reshape(2, 5, 2)
print(Ejercicio_9)


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [20]:
Ejercicio_10 = np.arange(1, 21).reshape(4, 5)
nuevo_Array5 = Ejercicio_10[::-1, ::-1]
print(nuevo_Array5)


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [21]:
Ejercicio_11 = np.zeros(10)
print(Ejercicio_11)
print("___________________________\n")
print(Ejercicio_11.nbytes)
print("___________________________\n")
Ejercicio_11[3] = 1  
print( Ejercicio_11)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
___________________________

80
___________________________

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [23]:
Ejercicio_12 = np.arange(10, 50)
vector_invertido = Ejercicio_12[::-1]
print( Ejercicio_12)
print("___________________________\n")
print(vector_invertido)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
___________________________

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [30]:
Ejercicio_14 = np.random.random((10, 10)) 
valor_minimo = Ejercicio_14.min()
valor_maximo = Ejercicio_14.max()

print(Ejercicio_14)
print("___________________________\n")
print(valor_minimo)
print("___________________________\n")
print(valor_maximo)


[[0.12476377 0.09125986 0.99864544 0.61105833 0.49659746 0.32275906
  0.70580502 0.5562202  0.62494965 0.41160108]
 [0.33587487 0.74977305 0.86373478 0.47435828 0.52254469 0.24121799
  0.34960566 0.5515335  0.8589756  0.79758162]
 [0.30653744 0.32250883 0.46359518 0.3497658  0.623743   0.84774248
  0.0418674  0.27278857 0.30546231 0.22125362]
 [0.2152324  0.12845501 0.61361437 0.3303574  0.44382604 0.01867377
  0.00697498 0.92166598 0.9350847  0.82451832]
 [0.8049459  0.94737652 0.32782699 0.10188657 0.7451389  0.40930602
  0.94823728 0.60757345 0.78416821 0.48878545]
 [0.60708978 0.72337456 0.99980064 0.72612906 0.28637213 0.98573862
  0.3742964  0.13522552 0.93657224 0.94334082]
 [0.63428885 0.27234233 0.99973165 0.595447   0.23062973 0.83365346
  0.67059155 0.5809334  0.75090148 0.34203445]
 [0.84908506 0.0159734  0.6728256  0.91004544 0.89168996 0.16737791
  0.70210804 0.62393727 0.78540299 0.53762466]
 [0.32547484 0.9552403  0.88372287 0.56200809 0.3559465  0.46232095
  0.6914285 

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [33]:
ejercicio_15 = np.random.random(30)  
media_Ejercicio_15 = ejercicio_15.mean()

print(ejercicio_15)
print(media_Ejercicio_15)


[0.46686704 0.09560716 0.44442792 0.44135857 0.78208353 0.11107001
 0.70791952 0.9343486  0.91163185 0.75828672 0.61064525 0.37488202
 0.85191435 0.35922672 0.17379397 0.56214203 0.86496644 0.88181013
 0.18264316 0.03094154 0.00922663 0.13153926 0.89286522 0.65253102
 0.89690972 0.44171785 0.61907144 0.77148091 0.72281937 0.75598804]
0.5480238671365566


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [ ]:
"""numeros_total = 8
ejercicio_16 = np.ones((numeros_total, numeros_total))
ejercicio_16[:1:-1, :1:-1] = 0

print(ejercicio_16)"""

#Ya no sé que hacer aquí

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [48]:
matriz = np.zeros((8, 8), dtype=int)
matriz[1::2, ::2] = 1
matriz[::2, 1::2] = 1

print(matriz)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [56]:
ejercicio_19 = np.random.random((5, 5))
media = np.mean(matriz)
desviacion = np.std(ejercicio_19)
matriz_normalizada = (ejercicio_19 - media) / desviacion

print( ejercicio_19)
print()
print(matriz_normalizada)


[[0.02968182 0.89983778 0.00263852 0.82464229 0.9574256 ]
 [0.47285822 0.27485888 0.59121355 0.72664103 0.75289436]
 [0.67205557 0.11558597 0.20933426 0.76341067 0.24761898]
 [0.32540647 0.20645675 0.18204651 0.8627589  0.98122196]
 [0.95905096 0.78119763 0.14033835 0.89815834 0.23750751]]

[[-1.25896123  1.37644186 -1.34086607  1.14870058  1.55085557]
 [ 0.08326766 -0.51640424  0.44172524  0.85188848  0.93140079]
 [ 0.68656791 -0.99878709 -0.71485579  0.96325106 -0.59890452]
 [-0.36331298 -0.72357077 -0.797501    1.26414269  1.62292653]
 [ 1.5557782   1.01712166 -0.92382067  1.37135542 -0.62952871]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [66]:
ejercicio_20 = np.arange(11)
print(ejercicio_20)
print("____________________________________\n")

ejercicio_20_2 = ejercicio_20.copy()
ejercicio_20_2[(ejercicio_20_2 >= 3) & (ejercicio_20_2 <= 8)] = -1
print( ejercicio_20_2)
print("____________________________________\n")
ejercicio_20_3 = ejercicio_20.copy()
ejercicio_20_3[(ejercicio_20_3 >= 3) & (ejercicio_20_3 <= 8)] * -1
print(ejercicio_20_3)



[ 0  1  2  3  4  5  6  7  8  9 10]
____________________________________

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
____________________________________

[ 0  1  2  3  4  5  6  7  8  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')